name = "rankmaster"
compatibility_date = "2024-12-01"

# Firebase configuration values
[vars]
FIREBASE_API_KEY = "AIzaSyBTCjmVvGhVpUer02EwW08toKkmpww6SlU"
FIREBASE_AUTH_DOMAIN = "rankmaster-1a740.firebaseapp.com"
FIREBASE_PROJECT_ID = "rankmaster-1a740"
FIREBASE_STORAGE_BUCKET = "rankmaster-1a740.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID = "678820485112"
FIREBASE_APP_ID = "1:678820485112:web:982ded15636867af74280d"

# Pages configuration
pages_build_output_dir = "dist"
