name = "019a502a-8c46-77d9-9d58-3bf28320a309"
compatibility_date = "2025-06-17"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "019a502a-8c46-77d9-9d58-3bf28320a309"
database_id = "019a502a-8c46-77d9-9d58-3bf28320a309"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "019a502a-8c46-77d9-9d58-3bf28320a309"
